### ISSUE TITLE
Add code of conduct to the site

### ISSUE THREAD

**Issue by NataliaLKB** [node-girls/node-girls-website#11]

**Comment by NataliaLKB** [comment]
Where should this go on the site? @iteles @nikhilaravi

**Comment by nikhilaravi** [comment]
@NataliaLKB I think it should be on a separate page or a link on the Upcoming Events page?

**Comment by iteles** [comment]
I like the idea of a separate page, it draws attention to how important it is. 

It'll throw off the symmetry of our nav though 🙈
We could link to it in the footer and every events page instead though?

**Comment by NataliaLKB** [comment]
I like that idea! So Code of Conduct on its own page with links in the Footer and the events page.

Sounds like a plan to me!

**Comment by iteles** [comment]
Happy to do this if others don't have time, but I won't have time til the weekend :+1:

**Comment by NataliaLKB** [comment]
Do you still have time to do this? If not, I can do this on Sunday I think :)

**Comment by iteles** [comment]
I have it in my calendar for this weekend - it will get done! Thanks for offering though :blush:

**Comment by NataliaLKB** [comment]
Great! Thank you!
