### ISSUE TITLE
Add a news feed?

### ISSUE THREAD

**Issue by NataliaLKB** [node-girls/node-girls-website#12]
Twitter feed on a side panel on all pages but the landing page.

What do you think @nikhilaravi @iteles ?

**Comment by iteles** [comment]
Having spent the day on the website, I think we need to rethink the positioning of this, but still very worthwhile!

**Comment by NataliaLKB** [comment]
I would say this is a stretch goal, and not something we need for the end of the week.

**Comment by nikhilaravi** [comment]
@NataliaLKB yes I agree! :)

**Comment by msmichellegar** [comment]
Going to close this so we can focus our energy on other things to make our life contributing to the website easier.
