### ISSUE TITLE
Mentors

### ISSUE THREAD

**Issue by NataliaLKB** [node-girls/node-girls-website#14]
Hey Mentors!

Can each of you post a picture, full name, twitter, and job title/position?

Thanks so much :smile:

**Comment by NataliaLKB** [comment]
@anniva @RachBLondon this is at you!!! Also @anniva your friend also came, can she post her picture and info here too!

**Comment by msmichellegar** [comment]
Think we've got this covered now. Any new mentors are welcome to make a PR.
