### ISSUE TITLE
Logo alignment

### ISSUE THREAD

**Issue by minaorangina** [node-girls/node-girls-website#15]
Was hanging around the node.js website and spotted something.

The letters in the official 'Node' logo are basically _**4 hollowed-out, identically sized hexagons**_ 
(I've never really noticed before).

Perhaps the 'Girls' in @heron2014 's awesome Node Girls logo should follow suit and be slightly adjusted, especially if @iteles is gonna order stickers?

This is what I mean:

![node-girls-hexagons](https://cloud.githubusercontent.com/assets/8915092/12704628/f826e374-c856-11e5-9695-32e5434cd166.png)

What do we reckon guys?

**Comment by iteles** [comment]
@minaorangina If @heron2014 has time, this would be awesome! See also https://github.com/node-girls/start-here/issues/8#issuecomment-177497581

**Comment by minaorangina** [comment]
Ah, didn't spot that issue.  Thanks :+1:

**Comment by heron2014** [comment]
@minaorangina well spotted :) if we settle for this sticker I will adjust it! @iteles how long usually takes to order stickers ? Just wonder how much time I have :)

**Comment by heron2014** [comment]
I have adjusted what I could: 

![nodegirlsngrnew](https://cloud.githubusercontent.com/assets/8476884/12751845/5377877c-c9b7-11e5-82a5-7771a913e654.png)

@minaorangina please have a look and check if all good, then I will send new svg to @NataliaLKB .

**Comment by iteles** [comment]
Any thoughts @minaorangina? :blush: 

Once this issue is closed, we can update the website and order the stickers :+1:

**Comment by minaorangina** [comment]
Yeah it's a :+1: from me!
