### ISSUE TITLE
Add team images and github profile links

### ISSUE THREAD

**Issue by nikhilaravi** [node-girls/node-girls-website#21]
@minaorangina @iteles @NataliaLKB @msmichellegar @nofootnotes @heron2014 @RachBLondon @anniva 

Can you all make a PR to add your image to the team page?
- add an image to the images/team folder
- add a link to the image in the css/styles.css file under the css class for your name e.g. 

``` js
.mina {
  background-image: url("../images/team/mina.jpg");
}
```
- find your name in the team.html file and add the link to the `a` tag e.g. 

``` js
   <div class="col s12 m6 l4 row center">
      <a href="http://github.com/nataliaLKB">
        <div class="team-image natalia"></div>
      </a>
      <h5>Natalia Baltazar</h5>
      <p>Developer at The Guardian</p>
    </div>
```

I have added profiles for most people but apologies if I have missed you off! Please add yourself by:
- copying the example code above and pasting it in the relevant div (either organisers or mentors)
- adding a css class with your name 

If there are any questions/problems please let me know. I can tidy up the file after everyone has made their additions!!

Or if this is too complicated just gitter me your photos and I can add them in!!

:blush:

**Comment by NataliaLKB** [comment]
@nikhilaravi I assigned you so you can make sure this is completed :).

**Comment by nikhilaravi** [comment]
@NataliaLKB  cool I'll close this when all the photos have been added

**Comment by NataliaLKB** [comment]
Closing as this has been done :)

**Comment by nikhilaravi** [comment]
cool!
