### ISSUE TITLE
Can't get back to home

### ISSUE THREAD

**Issue by minaorangina** [node-girls/node-girls-website#28]
@iteles @NataliaLKB @nikhilaravi Noticed there's no where to get back to the landing page from any of the other pages (apart from hitting back on the browser).  Might be nice to have a way to do so? :smile:

**Comment by iteles** [comment]
:laughing: Totally agree: https://github.com/node-girls/node-girls-website/pull/20#issuecomment-179851838

Thanks for opening the issue to capture this :+1:

**Comment by NataliaLKB** [comment]
Which do you guys like better: 

![image](https://cloud.githubusercontent.com/assets/8774970/12961325/c5598486-d037-11e5-9de0-ec9a31d129e4.png)

or

![image](https://cloud.githubusercontent.com/assets/8774970/12961341/e0e85bf0-d037-11e5-8fe3-1a82c5022682.png)

or something else?

**Comment by iteles** [comment]
@nataliaLKB I'm a fan of the first version!
I would try ou a version of that with the logo slightly bigger than the rest of the nav links just to see what it looks like too 😊

**Comment by NataliaLKB** [comment]
Thanks so much @iteles !!! I will send a PR with it in the center, with the logo slightly bigger. I will put a screen shot in the description.

**Comment by iteles** [comment]
Amazing, thanks @NataliaLKB !

**Comment by iteles** [comment]
_sigh_ Didn't mean to close that, so easy to do on mobile!!

**Comment by nikhilaravi** [comment]
@NataliaLKB yes I like the first version too! :+1:

**Comment by NataliaLKB** [comment]
This is fixed now!
