### ISSUE TITLE
Nav is off-center

### ISSUE THREAD

**Issue by iteles** [node-girls/node-girls-website#33]
We need to take another pass at the nav alignment.

On my screen it looks like this (note the unusually large gap between the 'Resources' and the 'Contact Us' links as well:
<img width="1778" alt="screen shot 2016-02-10 at 22 18 47" src="https://cloud.githubusercontent.com/assets/4185328/12963773/742acf0e-d044-11e5-920e-c607ee074d72.png">

**Comment by heron2014** [comment]
This issue remains on my screen: 

![nav-not-centered](https://cloud.githubusercontent.com/assets/8476884/13170509/61768c8a-d6e4-11e5-9021-8050fa337620.png)

**Comment by heron2014** [comment]
I have checked on laptop 15inch and this is the issue: 

![scrnode1-node-girls](https://cloud.githubusercontent.com/assets/8476884/13177621/3587c08e-d712-11e5-9495-b7635b7b6e50.jpg)

**Comment by NataliaLKB** [comment]
@iteles give the site a try on mobile, and let me know if this issue is fixed!

**Comment by msmichellegar** [comment]
No longer an issue as we don't have the logo in the nav.
