### ISSUE TITLE
Background not 100% viewport

### ISSUE THREAD

**Issue by heron2014** [node-girls/node-girls-website#40]
I think there is an issue with background (viewport), it is not perfectly 100% viewport. I need to scroll up a bit to move to another section, and coffee at the bottom is cut off because of that. 

Screenshot: 
![background](https://cloud.githubusercontent.com/assets/8476884/13170572/f0b353ba-d6e4-11e5-94db-7bf6f5e8634e.png)

Screenshot of background 100% viewport, issue with navbar  - moves off the screen. 

![perefct](https://cloud.githubusercontent.com/assets/8476884/13170614/449acecc-d6e5-11e5-9d55-650e76636840.png)

**Comment by heron2014** [comment]
This is another screenshot from laptop 15 inch with the same issue (background not covered on 100% viewport):

![node-girls-background-issue](https://cloud.githubusercontent.com/assets/8476884/13177531/b34de972-d711-11e5-9cf5-1b4b3fa3a929.jpg)

**Comment by NataliaLKB** [comment]
Closing as fixed by https://github.com/node-girls/node-girls-website/commit/62bc53ee97a165cadc579a46e6db44bfd0cea766
