### ISSUE TITLE
Sort out master/default branch

### ISSUE THREAD

**Issue by msmichellegar** [node-girls/node-girls-website#55]
Our `master` branch is kind of defunct at this point, since `gh-pages` is our default and `master` hasn't been updated in forever. I think we either need to delete the `master` branch altogether, or merge the changes and set up our GitHub pages to pull from `master` instead (which is [now possible](https://t.co/yHCDnPUS4Z)).

**Comment by iteles** [comment]
I favour the latter, `master` should really be our default production branch!

**Comment by msmichellegar** [comment]
Two years later, finally bloody fixed it!
