### ISSUE TITLE
Make main description more inclusive

### ISSUE THREAD

**Issue by msmichellegar** [node-girls/node-girls-website#57]
We need to update the main description on the front page of the site so we're more welcoming to non-binary folk, and also to widen the scope of our workshops to include just JavaScript, since some chapters are running classes for beginners too.

It's currently: "Node Girls runs free 1 day Node.js workshops. We aim to provide a friendly environment for women who are learning to code, supported by a community of experienced female mentors."

Proposing something like: "Node Girls runs free JavaScript and Node.js workshops. We aim to provide a friendly environment for women, non-binary and trans folk who are learning to code, supported by a community of experienced mentors."

Approve? Any other suggestions?

**Comment by ButenkoT** [comment]
I like this changes that you propose - I think it's right, more inclusive way.
It's hard for us to find enough female mentors for 80-100 attendees, so we accept guys mentors as well. If they really want to give back to community we should give them such an opportunity. Of course, we give preference for female mentors anyways.

**Comment by msmichellegar** [comment]
@ButenkoT Yep, that's why I took out "female" in the mentors bit! We know not every chapter can find enough non-male mentors to keep the events totally autonomous (as in, totally without men). As long as we're giving priority and keeping the leadership mostly autonomous I think that's cool :)

**Comment by NataliaLKB** [comment]
@msmichellegar sounds great!
