### ISSUE TITLE
I've filed a bug with a google developer

### ISSUE THREAD

**Issue by alexiamcdonald** [node-girls/node-girls-website#65]
A google developer has offered to fix the problem we have on google search. Let me know if it happens on any other search terms apart from `node girls melbourne` so I can let them know

**Comment by msmichellegar** [comment]
Amazing! I think a lot of people have found problems with just `node girls`, and also `node girls london`, or `node girls sydney`.

**Comment by msmichellegar** [comment]
I believe this is no longer a problem, going to close the issue. Thanks for your help (awhile back) @alexiamcdonald  ✨
